Nama : Aziz Dharmawan Apray
FTDS Batch 8

## Data Loading

In [1]:
import numpy as np
import pandas as pd

In [5]:
df = pd.read_csv('train.csv')
df.head()

,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,n_cores,...,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi,price_range
0,842,0,2.2,0,1,0,7,0.6,188,2,...,20,756,2549,9,7,19,0,0,1,1
1,1021,1,0.5,1,0,1,53,0.7,136,3,...,905,1988,2631,17,3,7,1,1,0,2
2,563,1,0.5,1,2,1,41,0.9,145,5,...,1263,1716,2603,11,2,9,1,1,0,2
3,615,1,2.5,0,0,0,10,0.8,131,6,...,1216,1786,2769,16,8,11,1,0,0,2
4,1821,1,1.2,0,13,1,44,0.6,141,2,...,1208,1212,1411,8,2,15,1,1,0,1

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   battery_power  2000 non-null   int64
 1   blue           2000 non-null   int64
 2   clock_speed    2000 non-null   float64
 3   dual_sim       2000 non-null   int64
 4   fc             2000 non-null   int64
 5   four_g         2000 non-null   int64
 6   int_memory     2000 non-null   int64
 7   m_dep          2000 non-null   float64
 8   mobile_wt      2000 non-null   int64
 9   n_cores        2000 non-null   int64
 10  pc             2000 non-null   int64
 11  px_height      2000 non-null   int64
 12  px_width       2000 non-null   int64
 13  ram            2000 non-null   int64
 14  sc_h           2000 non-null   int64
 15  sc_w           2000 non-null   int64
 16  talk_time      2000 non-null   int64
 17  three_g        2000 non-null   int64
 18  touch_screen   2000 non-null   int64
 19  wifi           2000 non-null   int64
 20  price_range    2000 non-null   int64
dtypes: float64(2), int64(19)
memory usage: 328.2 KB

In [9]:
# menghitung jumlah missing values

df.isnull().sum()

battery_power    0
blue             0
clock_speed      0
dual_sim         0
fc               0
four_g           0
int_memory       0
m_dep            0
mobile_wt        0
n_cores          0
pc               0
px_height        0
px_width         0
ram              0
sc_h             0
sc_w             0
talk_time        0
three_g          0
touch_screen     0
wifi             0
price_range      0
dtype: int64

In [10]:
df.describe()

,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,n_cores,...,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi,price_range
count,2000.000000,2000.0000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,...,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000
mean,1238.518500,0.4950,1.522250,0.509500,4.309500,0.521500,32.046500,0.501750,140.249000,4.520500,...,645.108000,1251.515500,2124.213000,12.306500,5.767000,11.011000,0.761500,0.503000,0.507000,1.500000
std,439.418206,0.5001,0.816004,0.500035,4.341444,0.499662,18.145715,0.288416,35.399655,2.287837,...,443.780811,432.199447,1084.732044,4.213245,4.356398,5.463955,0.426273,0.500116,0.500076,1.118314
min,501.000000,0.0000,0.500000,0.000000,0.000000,0.000000,2.000000,0.100000,80.000000,1.000000,...,0.000000,500.000000,256.000000,5.000000,0.000000,2.000000,0.000000,0.000000,0.000000,0.000000
25%,851.750000,0.0000,0.700000,0.000000,1.000000,0.000000,16.000000,0.200000,109.000000,3.000000,...,282.750000,874.750000,1207.500000,9.000000,2.000000,6.000000,1.000000,0.000000,0.000000,0.750000
50%,1226.000000,0.0000,1.500000,1.000000,3.000000,1.000000,32.000000,0.500000,141.000000,4.000000,...,564.000000,1247.000000,2146.500000,12.000000,5.000000,11.000000,1.000000,1.000000,1.000000,1.500000
75%,1615.250000,1.0000,2.200000,1.000000,7.000000,1.000000,48.000000,0.800000,170.000000,7.000000,...,947.250000,1633.000000,3064.500000,16.000000,9.000000,16.000000,1.000000,1.000000,1.000000,2.250000
max,1998.000000,1.0000,3.000000,1.000000,19.000000,1.000000,64.000000,1.000000,200.000000,8.000000,...,1960.000000,1998.000000,3998.000000,19.000000,18.000000,20.000000,1.000000,1.000000,1.000000,3.000000

In [11]:
df.describe().T     # transpose

,count,mean,std,min,25%,50%,75%,max
battery_power,2000.0,1238.51850,439.418206,501.0,851.75,1226.0,1615.25,1998.0
blue,2000.0,0.49500,0.500100,0.0,0.00,0.0,1.00,1.0
clock_speed,2000.0,1.52225,0.816004,0.5,0.70,1.5,2.20,3.0
dual_sim,2000.0,0.50950,0.500035,0.0,0.00,1.0,1.00,1.0
fc,2000.0,4.30950,4.341444,0.0,1.00,3.0,7.00,19.0
four_g,2000.0,0.52150,0.499662,0.0,0.00,1.0,1.00,1.0
int_memory,2000.0,32.04650,18.145715,2.0,16.00,32.0,48.00,64.0
m_dep,2000.0,0.50175,0.288416,0.1,0.20,0.5,0.80,1.0
mobile_wt,2000.0,140.24900,35.399655,80.0,109.00,141.0,170.00,200.0
n_cores,2000.0,4.52050,2.287837,1.0,3.00,4.0,7.00,8.0
pc,2000.0,9.91650,6.064315,0.0,5.00,10.0,15.00,20.0
px_height,2000.0,645.10800,443.780811,0.0,282.75,564.0,947.25,1960.0
px_width,2000.0,1251.51550,432.199447,500.0,874.75,1247.0,1633.00,1998.0
ram,2000.0,2124.21300,1084.732044,256.0,1207.50,2146.5,3064.50,3998.0
sc_h,2000.0,12.30650,4.213245,5.0,9.00,12.0,16.00,19.0
sc_w,2000.0,5.76700,4.356398,0.0,2.00,5.0,9.00,18.0
talk_time,2000.0,11.01100,5.463955,2.0,6.00,11.0,16.00,20.0
three_g,2000.0,0.76150,0.426273,0.0,1.00,1.0,1.00,1.0
touch_screen,2000.0,0.50300,0.500116,0.0,0.00,1.0,1.00,1.0
wifi,2000.0,0.50700,0.500076,0.0,0.00,1.0,1.00,1.0
price_range,2000.0,1.50000,1.118314,0.0,0.75,1.5,2.25,3.0

In [17]:
# mencari rata-rata

df['sc_w'].mean()

5.767

In [18]:
# atau
df.sc_w.mean()

5.767

In [22]:
df.dual_sim.unique()    # mengetahui apa saja kategorinya

array([0, 1], dtype=int64)

In [23]:
df.dual_sim.nunique()    # mengetahui jumlah kategorinya

2

In [25]:
df.n_cores.unique()

array([2, 3, 5, 6, 1, 8, 4, 7], dtype=int64)

In [26]:
df[df['n_cores'].isin([2,4])]       # filter n_cores yang nilainya 2 dan 4 saja

,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,n_cores,...,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi,price_range
0,842,0,2.2,0,1,0,7,0.6,188,2,...,20,756,2549,9,7,19,0,0,1,1
4,1821,1,1.2,0,13,1,44,0.6,141,2,...,1208,1212,1411,8,2,15,1,1,0,1
7,1954,0,0.5,1,0,0,24,0.8,187,4,...,512,1149,700,16,3,5,1,1,1,0
12,1815,0,2.8,0,2,0,33,0.6,159,4,...,607,748,1482,18,0,2,1,0,0,1
13,803,1,2.1,0,7,0,17,1.0,198,4,...,344,1440,2680,7,1,4,1,0,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1974,915,1,0.5,1,9,1,33,0.3,199,2,...,503,986,2156,7,3,13,1,1,0,1
1977,1379,0,1.1,1,1,1,18,0.2,129,2,...,838,885,2358,10,5,15,1,1,0,2
1986,1139,1,0.9,1,6,1,58,0.5,161,2,...,742,999,1850,9,4,8,1,0,0,1
1987,618,1,1.0,0,9,1,13,0.1,80,4,...,591,724,1424,15,12,7,1,1,0,0
1996,1965,1,2.6,1,0,0,39,0.2,187,4,...,915,1965,2032,11,10,16,1,1,1,2

In [30]:
df.loc[:, 'battery_power' : 'clock_speed']      # loc berdasarkan label --> df.loc[namaBaris, namaKolom]

      battery_power  blue  clock_speed
0               842     0          2.2
1              1021     1          0.5
2               563     1          0.5
3               615     1          2.5
4              1821     1          1.2
...             ...   ...          ...
1995            794     1          0.5
1996           1965     1          2.6
1997           1911     0          0.9
1998           1512     0          0.9
1999            510     1          2.0

[2000 rows x 3 columns]

In [33]:
df.iloc[:,0:3]      # iloc berdasarkan indeks --> df.loc[indeksBaris, indeksKolom]

      battery_power  blue  clock_speed
0               842     0          2.2
1              1021     1          0.5
2               563     1          0.5
3               615     1          2.5
4              1821     1          1.2
...             ...   ...          ...
1995            794     1          0.5
1996           1965     1          2.6
1997           1911     0          0.9
1998           1512     0          0.9
1999            510     1          2.0

[2000 rows x 3 columns]

In [34]:
df.iloc[:3,:3]

   battery_power  blue  clock_speed
0            842     0          2.2
1           1021     1          0.5
2            563     1          0.5

## Function, Looping, dan If

hitung **luas** jika dual_sim = 1, jika tidak maka hitung **kurang**:

- luas = tinggi(px_height)* lebar(px_width)
- kurang = tinggi -lebar
- buat kolom baru yang berisi hasil dari perhitungan luas dan kurang

In [35]:
def luas(tinggi,lebar):
    hasil = tinggi * lebar
    return hasil

def kurang(tinggi,lebar):
    hasil_k = tinggi - lebar
    return hasil_k

In [43]:
df_new = df.copy()

In [66]:
lk = []     # untuk masukan hasil kedalam list
g = 0      # indeks baris

for i in df_new['dual_sim']:
    if i == 1:
        lk.append(luas(df_new['px_height'][g], df_new['px_width'][g]))
    else:
        lk.append(luas(df_new['px_height'][g], df_new['px_width'][g]))
    print(df_new['px_height'][g])
    g += 1

df_new['l/k'] = lk      # bikin kolom 'l/k' dengan nilai list 'lk'

20
905
1263
1216
1208
1004
381
512
386
1137
248
151
607
344
356
862
984
441
658
902
1314
974
407
466
201
291
550
511
187
1171
1358
413
85
178
311
1134
429
609
347
1448
434
1725
685
880
1580
186
202
27
1025
885
1042
1382
546
1013
690
667
822
581
265
127
916
361
322
753
504
651
1565
108
459
205
570
1172
160
4
763
339
1040
166
1168
990
319
1397
708
1077
928
516
96
1025
666
557
1605
1226
769
403
177
942
651
1572
476
1233
836
824
391
320
325
125
846
1770
293
1633
1198
768
70
117
1158
1055
635
322
275
1445
550
1242
597
538
59
819
179
1259
396
713
262
622
327
522
313
226
605
692
1386
304
1590
229
839
507
436
756
387
1265
1852
875
140
577
975
510
583
674
1125
747
1612
311
116
554
811
730
577
660
450
1223
1109
45
299
506
635
1045
393
650
433
839
1176
650
218
564
986
561
65
420
1365
619
849
611
953
642
1417
247
710
718
1100
59
938
825
286
1273
295
852
710
1277
129
690
701
309
213
1112
199
55
1230
1052
541
55
809
1738
404
262
759
42
397
964
233
1022
411
954
1528
416
638
231
574
148
730
564
1290
632
529
1273
667
1170
169
105
793
490
1201
246
417
1177
78
323
707
457
356
936
912
179
1914
526
156
344
865
1552
546
1097
372
1285
1242
302
594
303
1858
403
32
590
235
630
357
246
475
1054
555
607
1360
142
681
104
637
410
1830
802
311
56
344
1053
221
506
1728
63
418
854
178
1869
185
170
454
866
44
1331
1285
741
520
114
1153
474
39
419
584
312
19
207
363
209
159
649
1132
1392
1001
712
418
384
119
627
1086
195
14
745
253
333
629
707
1314
1715
513
13
1243
300
58
1107
134
275
176
1236
336
1116
1010
205
1453
788
1301
463
188
1028
1419
1471
168
1125
130
481
1411
79
1187
561
96
77
493
1173
964
634
639
127
431
71
111
356
798
747
408
373
1362
475
743
447
42
30
162
347
346
727
180
1641
269
250
1186
77
507
379
264
1486
694
579
495
315
329
548
531
191
823
96
841
195
21
235
1417
286
649
966
1172
270
781
418
126
228
1091
1452
674
398
449
1184
675
1792
177
1013
1058
592
810
533
558
681
1017
765
1176
947
1314
609
754
619
453
205
282
130
494
275
447
281
6
292
164
631
897
268
861
331
1064
509
622
957
494
236
980
1789
831
902
636
831
518
233
725
170
157
1142
840
401
395
48
982
478
581
1215
594
683
536
83
905
249
803
459
584
1596
418
364
946
186
1428
1613
1127
691
1802
751
859
187
206
1673
710
1331
263
97
129
1213
189
628
320
837
1087
781
251
262
767
1226
389
920
1027
271
369
1258
417
1345
613
912
666
236
186
416
430
168
1467
179
159
120
762
600
286
1350
27
1597
1177
402
577
52
364
934
250
214
612
1111
163
202
729
1079
361
338
1698
1052
1108
951
1197
473
1294
410
178
782
434
464
137
492
1250
385
427
1024
240
886
1233
183
88
1016
80
611
569
304
276
1131
551
436
553
1391
981
680
687
1060
217
1140
304
504
832
935
446
942
897
1208
159
632
1308
1002
1331
150
1248
108
320
437
295
1058
79
593
693
300
234
1545
59
1103
91
177
58
447
942
88
371
1446
181
1311
1791
1568
706
871
1074
501
271
920
1171
293
833
485
182
207
1698
165
1086
192
1156
377
709
729
543
553
526
637
113
1114
461
1430
304
471
806
80
204
545
112
1331
1055
609
290
1039
1485
1122
462
1384
1502
589
82
68
689
208
1339
722
717
433
1298
186
1397
618
1214
613
649
193
22
1464
280
690
39
337
1036
1347
22
327
778
482
591
229
901
715
172
681
867
286
451
1119
526
1299
217
1109
434
671
1404
856
381
85
562
1111
209
997
91
730
606
445
286
985
1617
375
1795
486
757
273
491
762
448
231
1713
438
68
698
510
965
1399
532
8
154
198
860
461
109
193
961
243
1626
480
123
400
190
626
1
548
632
349
1686
1455
95
580
297
951
667
1047
408
1150
333
641
653
103
517
785
531
564
761
1179
673
472
412
977
359
224
714
195
843
308
522
364
806
518
519
792
382
214
859
342
713
172
118
540
18
987
535
1092
327
517
994
491
268
210
144
729
82
188
150
1222
331
1178
347
75
492
65
881
351
1842
758
1323
1175
1092
647
1102
319
215
945
381
546
1096
575
519
342
291
1091
352
165
385
1920
396
1134
721
687
777
176
458
485
641
798
256
370
191
1571
276
573
160
90
138
983
275
149
42
793
625
521
1530
442
152
1242
29
501
87
648
521
120
985
341
751
993
43
1262
361
104
618
815
1587
138
584
750
820
8
171
960
160
612
709
624
538
1295
1164
829
199
825
519
169
1734
76
1698
819
387
985
970
767
512
56
590
462
126
578
655
1028
88
1692
358
64
259
236
873
858
1405
237
650
1949
541
361
335
1638
1109
111
1285
1480
322
1220
511
1011
629
140
1081
297
1512
275
1136
1145
477
954
741
547
1194
146
471
169
1895
1537
236
821
466
393
400
774
284
465
705
38
51
850
349
387
706
951
179
426
653
1578
280
251
1463
1432
477
1122
145
416
847
868
594
518
663
371
1749
586
409
35
1008
442
983
875
952
244
65
1749
716
433
134
179
804
787
704
991
379
489
1518
855
1261
115
1203
545
818
42
1103
168
719
163
1162
626
329
330
956
1140
217
271
444
1003
227
253
88
334
1281
168
898
46
118
1187
1191
526
346
89
137
1226
473
368
239
622
654
853
686
992
115
275
461
1428
614
193
1105
398
480
775
1482
154
454
737
419
853
1211
314
172
527
874
674
657
475
1209
15
293
813
173
457
533
912
798
412
130
201
299
1277
626
378
333
805
1901
1573
360
20
98
703
273
919
982
879
1287
1109
211
1058
532
290
890
327
1260
570
621
328
1307
497
219
1163
24
468
1272
503
1495
1333
267
149
1070
206
158
48
249
935
140
184
238
800
211
670
725
81
1211
1362
945
1043
444
311
812
202
531
404
954
274
956
1438
1446
692
777
1157
454
478
217
468
1107
626
485
43
322
880
1511
667
765
614
925
1185
1706
347
1603
806
1207
431
179
423
1131
925
62
800
211
81
667
405
678
1619
935
864
1495
870
1379
1055
220
419
1111
1097
447
273
590
116
306
300
1259
1573
1392
113
526
1209
655
1123
692
796
1021
995
1244
293
1240
759
398
358
403
211
194
1076
1238
229
327
135
5
715
511
549
420
838
314
739
62
3
963
1438
1621
19
887
567
584
496
1245
682
724
1384
257
17
983
439
925
409
293
384
149
447
717
195
153
1699
501
530
396
670
193
351
846
111
1213
755
1406
497
1826
50
817
901
212
329
837
248
632
366
174
882
688
263
118
1012
586
294
818
426
151
409
641
958
1328
354
1709
1099
783
194
238
919
758
1039
1054
122
100
1221
312
599
1274
62
315
1123
1878
318
574
1353
86
340
602
963
127
142
274
371
788
395
643
854
1335
1541
382
846
960
154
468
1094
272
165
394
629
831
903
923
362
693
1250
1135
66
924
204
376
1083
229
875
35
18
103
105
168
18
659
534
285
482
1571
605
158
1573
127
343
289
1703
1482
907
491
287
1151
1024
1085
991
1052
1078
98
396
323
410
1750
1475
1836
283
539
440
397
204
347
1003
0
264
543
467
875
1116
1325
1313
552
335
50
593
268
382
443
576
596
115
356
10
1399
68
643
809
683
56
492
699
290
23
394
713
1063
1421
623
83
1563
777
83
203
938
1077
773
332
570
742
1420
1801
1693
31
1098
1765
887
760
486
2
202
90
469
86
1180
140
1100
194
440
1563
163
192
837
356
155
1032
40
1194
1179
902
58
1385
614
672
1088
499
157
485
571
431
499
563
944
1138
161
126
15
500
203
961
608
277
114
630
404
248
225
699
649
416
1310
930
835
664
460
778
225
785
1581
9
7
174
437
278
1288
979
56
913
282
322
1252
1128
606
655
954
68
134
922
1874
251
1362
281
224
778
546
397
386
214
461
125
335
342
625
494
1145
600
484
199
21
885
308
1015
1303
406
124
150
108
90
588
1028
776
278
897
651
1010
737
1399
376
1117
234
691
380
603
117
766
1499
1175
988
190
674
518
1618
857
371
73
98
395
1064
712
774
1012
730
777
973
245
937
937
574
678
82
398
1096
1419
157
430
1524
1649
254
1790
1438
1304
813
948
1161
867
181
754
242
405
1569
105
978
725
657
1147
910
295
26
332
519
161
1080
649
71
744
437
115
547
495
1466
117
760
764
776
53
371
728
1791
606
1225
419
367
1230
267
273
705
214
424
84
605
1175
657
371
833
102
1299
258
56
443
1279
313
523
919
570
380
119
296
358
1364
424
961
431
950
647
1960
116
306
808
94
380
593
1684
1221
410
600
189
308
148
297
1050
1191
1399
1658
1153
35
553
46
207
67
818
1257
138
11
889
831
713
527
1284
911
1047
123
406
927
407
1041
781
1191
103
125
919
536
638
639
496
686
1064
240
525
348
1262
1899
258
1188
730
484
547
800
347
679
1224
948
366
223
1619
332
167
782
881
91
487
120
1626
74
634
334
931
921
805
1057
616
740
542
344
211
79
887
670
383
718
144
1442
291
1352
209
861
426
266
523
40
262
623
4
1001
334
453
952
321
1451
1048
398
417
470
1217
298
36
85
655
167
212
617
271
159
786
46
645
1371
881
449
338
1332
119
256
428
1546
1210
789
390
110
1330
674
253
317
183
892
388
52
914
287
773
675
367
510
1325
1661
665
662
0
284
661
757
560
470
146
1315
533
560
405
227
479
227
149
88
114
662
441
888
664
64
747
956
776
652
1168
201
724
599
3
1652
190
1171
1081
1211
976
675
455
42
1196
503
1694
306
838
291
173
1017
698
610
223
206
1457
742
591
347
241
743
4
576
888
528
1222
915
868
336
483

In [64]:
df_new.iloc[:11, 5:]

,four_g,int_memory,m_dep,mobile_wt,n_cores,pc,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi,price_range,l/k
0,0,7,0.6,188,2,2,20,756,2549,9,7,19,0,0,1,1,15120
1,1,53,0.7,136,3,6,905,1988,2631,17,3,7,1,1,0,2,1799140
2,1,41,0.9,145,5,6,1263,1716,2603,11,2,9,1,1,0,2,2167308
3,0,10,0.8,131,6,9,1216,1786,2769,16,8,11,1,0,0,2,2171776
4,1,44,0.6,141,2,14,1208,1212,1411,8,2,15,1,1,0,1,1464096
5,0,22,0.7,164,1,7,1004,1654,1067,17,1,10,1,0,0,1,1660616
6,1,10,0.8,139,8,10,381,1018,3220,13,8,18,1,0,1,3,387858
7,0,24,0.8,187,4,0,512,1149,700,16,3,5,1,1,1,0,588288
8,0,53,0.7,174,7,14,386,836,1099,17,1,20,1,0,0,0,322696
9,1,9,0.1,93,5,15,1137,1224,513,19,10,12,1,0,0,0,1391688
10,0,9,0.1,182,5,1,248,874,3946,5,2,7,0,0,0,3,216752

In [61]:
# filter dual sim=1 dan fc ganjil

df_new[
    (df_new['dual_sim'] == 1) &
    (df_new['fc'] % 2 == 1)
]

,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,n_cores,...,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi,price_range,l/k
5,1859,0,0.5,1,3,0,22,0.7,164,1,...,1654,1067,17,1,10,1,0,0,1,1660616
17,595,0,0.9,1,7,1,23,0.1,121,3,...,810,3752,10,2,18,1,1,0,3,357210
18,1131,1,0.5,1,11,0,49,0.6,101,5,...,878,1835,19,13,16,1,1,0,1,577724
24,503,0,1.2,1,5,1,8,0.4,111,3,...,1245,2583,11,0,12,1,0,0,1,250245
26,519,1,1.6,1,7,1,51,0.3,132,4,...,645,3763,16,1,4,1,0,1,3,354750
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1974,915,1,0.5,1,9,1,33,0.3,199,2,...,986,2156,7,3,13,1,1,0,1,495958
1977,1379,0,1.1,1,1,1,18,0.2,129,2,...,885,2358,10,5,15,1,1,0,2,741630
1992,674,1,2.9,1,1,0,21,0.2,198,3,...,1809,1180,6,3,4,1,1,1,0,1041984
1997,1911,0,0.9,1,1,1,36,0.7,108,8,...,1632,3057,9,1,5,1,1,0,3,1416576
1999,510,1,2.0,1,5,1,45,0.9,168,6,...,754,3919,19,4,2,1,1,1,3,364182

In [68]:
# save file hasil df_new ke file baru

df_new.to_csv('train_rev.csv')